### ISSUE TITLE
Plug-in crashs

### ISSUE THREAD

**Issue by bender-rulez** [macnow/homebridge-platform-eq3btsmart#1]
SlowBuffer.makeFastBuffer(this.parent, this, this.offset, this.length);
} has no method 'from'
    at Object.eq3BTSmartAccessory (/usr/lib/node_modules/homebridge-platform-eq3btsmart/index.js:60:27)
    at null._onTimeout (/usr/lib/node_modules/homebridge-platform-eq3btsmart/index.js:32:31)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by macnow** [comment]
Are you using nodejs 4.x?

**Comment by bender-rulez** [comment]
No, v0.10.41 on BananaPi

**Comment by macnow** [comment]
I think that your problem comes from an outdated version of NodeJS. Maybe you should consider to upgrade it to the latest version. I'm using version 6.x.

**Comment by bender-rulez** [comment]
You should use 

noble.startScanning([], true); // any service UUID, allow duplicates

instead of noble.startScanning(); 

because, multiple thermostats will be found than!

**Comment by macnow** [comment]
@bender-rulez i have three thermostats and they worked already without this change
