### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by sthonnard** [macnow/homebridge-platform-eq3btsmart#10]
Hello,

I have 4 bluetooth thermostats. When running it detects them but raises an error about same UUID:

[2/19/2018, 9:11:20 PM] Loaded plugin: homebridge-platform-eq3btsmart
[2/19/2018, 9:11:20 PM] Registering platform 'homebridge-platform-eq3btsmart.eq3BTSmart'
[2/19/2018, 9:11:20 PM] ---
[2/19/2018, 9:11:20 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/19/2018, 9:11:20 PM] ---
[2/19/2018, 9:11:20 PM] Loading 1 platforms...
[2/19/2018, 9:11:20 PM] [Thermo] Initializing eq3BTSmart platform...
[2/19/2018, 9:11:20 PM] [Thermo] EQ3 - Discovering devices...
[2/19/2018, 9:11:35 PM] [Thermo] EQ3 - Found 4 devices.
[2/19/2018, 9:11:35 PM] [Thermo] Initializing platform accessory 'unknown'...
[2/19/2018, 9:11:35 PM] [Thermo] Initializing platform accessory 'unknown'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4e45af10-4006-4ab9-81d7-46e595213bcb
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-platform-eq3btsmart/index.js:35:21)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

Any suggestions?

**Comment by sthonnard** [comment]
Additional:
I have added some logging and the 4 devices are well detected with a correct id. Only the address is unknown for some of them.
function eq3BTSmartAccessory(log, device) {
    this.log = log;
    this.device = device;
    this.name = device.address;
    this.temperature = 19;
    this.targetTemperature = 19;
    this.heatingCoolingState = Characteristic.CurrentHeatingCoolingState.HEAT;
    this.targetHeatingCoolingState = Characteristic.TargetHeatingCoolingState.AUTO;
    this.temperatureDisplayUnits = Characteristic.TemperatureDisplayUnits.CELSIUS;
    this.command = Buffer.from([0x03]);
    this.refreshing = 0;

this.log('EQ3 - device '+device + ' '+device.address );
    this.initDevice();
}



[2/22/2018, 7:39:21 AM] [Thermo] EQ3 - device {"id":"e1f3705041c24f32bb3c2021f8661f50","address":"unknown","addressType":"unknown","connectable":true,"advertisement":{"localName":"CC-RT-BLE","manufacturerData":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0]},"serviceData":[],"serviceUuids":[]},"rssi":-67,"state":"disconnected"} unknown
[2/22/2018, 7:39:21 AM] [Thermo] EQ3 - device {"id":"6ee0107098f94c188912d33ff01b76c9","address":"unknown","addressType":"unknown","connectable":true,"advertisement":{"localName":"CC-RT-BLE","manufacturerData":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0]},"serviceData":[],"serviceUuids":[]},"rssi":-71,"state":"disconnected"} unknown
[2/22/2018, 7:39:21 AM] [Thermo] EQ3 - device {"id":"f24be4ecf45c483887e41ef8d35db63c","address":"unknown","addressType":"unknown","connectable":true,"advertisement":{"localName":"CC-RT-BLE","manufacturerData":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0]},"serviceData":[],"serviceUuids":[]},"rssi":-69,"state":"disconnected"} unknown
[2/22/2018, 7:39:21 AM] [Thermo] EQ3 - device {"id":"4ad19553149c4ec3a6beca58e9dfff59","address":"00:1a:22:06:46:ff","addressType":"unknown","connectable":true,"advertisement":{"localName":"CC-RT-BLE","manufacturerData":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0]},"serviceData":[],"serviceUuids":[]},"rssi":-76,"state":"disconnected"} 00:1a:22:06:46:ff


EDIT: I achieved to make it work by using another plugin, homebridge-eq3ble, hence issue could come from this plugin
