### ISSUE TITLE
eq3BTSmart not registered

### ISSUE THREAD

**Issue by serverpaul** [macnow/homebridge-platform-eq3btsmart#11]
At first I installed the plugin and then I inserted `{
    "platform": "eq3BTSmart"
}` into the config.json using copy+paste.
After a restart of Homebridge, I got this:

`[10/19/2020, 10:40:01 AM] Error: The requested platform 'eq3BTSmart' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)`

**Comment by jkorinth** [comment]
Same here. Is there a solution?

**Comment by serverpaul** [comment]
hi, I switched to this plugin: [https://github.com/maxnowack/homebridge-eq3ble](url)
Its almost working. I get the symbol for the thermostat in the home app, but i get no temperature.

**Comment by jkorinth** [comment]
Tried that, too. :-) Could not find a way to get the BLE MAC address via iOS/Mac, so I could not pair the thermostat.

**Comment by serverpaul** [comment]
Just download Xcode 11.4 with Bluetooth Explorer. Then search for all BLE products an you'll find a device named "CC-BT-CLE" or something like that.
You should find the program on the apple developer site.

**Comment by kjyv** [comment]
This is probably because bluetooth-hci-socket was not properly build (because it is not compatible with nodejs > 9).
I've managed to make it work on my raspberry pi by first installing the plugin, then manually installing 
`sudo npm install -g @abandonware/bluetooth-hci-socket --unsafe-perm`, then run
`sudo cp -R /usr/lib/node_modules/@abandonware/bluetooth-hci-socket/ /usr/lib/node_modules/homebridge-platform-eq3btsmart/node_modules/bluetooth-hci-socket`

My device was manually paired before (make sure bluetooth is enabled) and I can set temperature and manual/auto mode.

**Comment by kjyv** [comment]
I've added a pull request that should fix this
