### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-platform-eq3btsmart

### ISSUE THREAD

**Issue by horstulf** [macnow/homebridge-platform-eq3btsmart#6]
Hi all,

Can someone help me please with the following error I receive (Rasp Pi 1 + Jessie):

*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-09-29 22:57:42] **Plugin /usr/local/lib/node_modules/homebridge-eq3ble does not contain a package.json.**
[2017-09-29 22:57:55] ====================
[2017-09-29 22:57:55] **ERROR LOADING PLUGIN homebridge-platform-eq3btsmart:**
[2017-09-29 22:57:55] **Error: Cannot find module '../build/Release/binding.node'**
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-eq3btsmart/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-eq3btsmart/node_modules/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[2017-09-29 22:57:55] ====================
[2017-09-29 22:57:55] config.json (/root/.homebridge/config.json) not found.

Thanks a lot for your help!

**Comment by NexSabre** [comment]
Yop, I've got this same issue. Few days ago I install this plugin and everything goes without problems. Today, when I tried to reinstall, I get this same error.

**Comment by faltim** [comment]
Hey, I have the same issue. Is there a solution?
